project_id = "ydgjuzocrfeobptjyvrt"

[functions.analyze-sales]
verify_jwt = false

[functions.google-trends]
verify_jwt = false

[functions.summer-trends]
verify_jwt = false

[functions.chat-with-data]
verify_jwt = false
